// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reservations.Database;

namespace Reservations.Database.Migrations
{
    [DbContext(typeof(ReservationsContext))]
    [Migration("20180930014200_Reservations-0.1")]
    partial class Reservations01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Reservations.Database.Models.ExtraTableEntry", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GuestTableEntryId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GuestTableEntryId");

                    b.ToTable("Extras");
                });

            modelBuilder.Entity("Reservations.Database.Models.GuestTableEntry", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Status");

                    b.Property<int>("TotalExtras");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Reservations.Database.Models.ExtraTableEntry", b =>
                {
                    b.HasOne("Reservations.Database.Models.GuestTableEntry")
                        .WithMany()
                        .HasForeignKey("GuestTableEntryId");
                });
#pragma warning restore 612, 618
        }
    }
}
