version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy to $DEPLOY_USER@$DEPLOY_IP
          command: |
            ssh $DEPLOY_USER@$DEPLOY_IP "bash deploy.sh"
