version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
        name: Sync deployment script
        command:
          scp deploy.sh $DEPLOY_USER@$DEPLOY_IP:~/.
      - run:
          name: Running deployment script
          command: |
            ssh $DEPLOY_USER@$DEPLOY_IP "bash deploy.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master